
using System.Text.Json.Serialization;
using Tavstal.KonkordLauncher.Common.Models.Json;
using Tavstal.KonkordLauncher.Core.Enums;
using Tavstal.KonkordLauncher.Core.Helpers.Serialization;

namespace Tavstal.KonkordLauncher.Common.Models;

/// <summary>
/// Represents a launcher instance configuration, including its identity, Minecraft version,
/// grouping metadata, and runtime settings.
/// </summary>
public class Instance
{
    /// <summary>
    /// Gets or sets the unique identifier for this instance.
    /// A new GUID is generated by default when the instance is created.
    /// </summary>
    [JsonPropertyName("id")] 
    public string Id { get; set; } = Guid.NewGuid().ToString();
    
    /// <summary>
    /// Gets or sets the display name of the instance.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; set; }
    
    /// <summary>
    /// Gets or sets the optional group this instance belongs to.
    /// </summary>
    [JsonPropertyName("group")]
    public string? Group { get; set; }
    
    /// <summary>
    /// Gets or sets the optional icon path associated with this instance.
    /// </summary>
    [JsonPropertyName("iconPath")]
    public string? IconPath { get; set; }
    
    /// <summary>
    /// Gets or sets the Minecraft version used by this instance.
    /// </summary>
    [JsonPropertyName("minecraftVersion")]
    public required string MinecraftVersion { get; set; }
    
    /// <summary>
    /// Gets or sets an optional custom version label or override.
    /// </summary>
    [JsonPropertyName("customVersion")]
    public string? CustomVersion { get; set; }
    
    /// <summary>
    /// Gets or sets the Minecraft kind or edition represented by this instance.
    /// </summary>
    [JsonPropertyName("kind")]
    public EMinecraftKind Kind { get; set; }
    
    /// <summary>
    /// Gets or sets the game directory used by this instance.
    /// </summary>
    [JsonPropertyName("gameDirectory")]
    public string? GameDirectory { get; set; }
    
    /// <summary>
    /// Gets or sets the instance configuration settings.
    /// </summary>
    [JsonPropertyName("settings")]
    public required InstanceConfig.InstanceConfig Config { get; set; }

    /// <summary>
    /// Gets the full path to the resource configuration file for this instance.
    /// </summary>
    /// <returns>
    /// A path combining <see cref="GameDirectory"/> with <c>resources.json</c>.
    /// </returns>
    public string GetResourceConfigPath() => Path.Combine(GameDirectory!, "resources.json");

    /// <summary>
    /// Asynchronously retrieves the instance resources.
    /// </summary>
    /// <returns>A list of instance resources, or null if none are found.</returns>
    public async Task<List<InstanceResource>?> GetInstanceResourcesAsync()
    {
        string path = GetResourceConfigPath();
        if (!File.Exists(path))
            return null;
        return await JsonHelper.ReadJsonFileAsync<List<InstanceResource>>(path, CommonJsonContex.Default.ListInstanceResource);
    }

    /// <summary>
    /// Gets the default JVM arguments used to launch Minecraft with recommended GC and networking settings.
    /// </summary>
    /// <returns>A string containing the default JVM argument list.</returns>
    public static string GetDefaultJVMArgs()
    {
        return "-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Djava.net.preferIPv4Stack=true";
    }
}