<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <AssemblyTitle>KonkordLauncherCore</AssemblyTitle>
      <Description>Minecraft-focused backend library for launching, installing, and managing game instances, assets, Java runtimes, mod loaders, authentication, and version metadata.</Description>
      <Company>Tavstal</Company>
      <Product>KonkordLauncherCore</Product>
      <Copyright>Copyright © 2026 Tavstal</Copyright>
      <ComVisible>false</ComVisible>
      <Guid>6824C219-9D48-42E5-8207-FE6A576D881F</Guid>
      <AssemblyVersion>2.0.0.0</AssemblyVersion>
      <FileVersion>2.0.0</FileVersion>
      <Version>2.0.0</Version>
      
      <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tavstal.KonkordLauncher.Core</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<Deterministic>false</Deterministic>

      <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hardware.Info" Version="101.1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.7" />
    <PackageReference Include="NbtLib" Version="1.0.1" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.7" />
    <PackageReference Include="MinecraftSkinRender" Version="1.0.0" />
    <PackageReference Include="MinecraftSkinRender.Image" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fmllib\argo-2.25.jar" />
    <EmbeddedResource Include="Assets\Fmllib\argo-small-3.2.jar" />
    <EmbeddedResource Include="Assets\Fmllib\asm-all-4.0.jar" />
    <EmbeddedResource Include="Assets\Fmllib\asm-all-4.1.jar" />
    <EmbeddedResource Include="Assets\Fmllib\bcprov-jdk15on-147.jar" />
    <EmbeddedResource Include="Assets\Fmllib\bcprov-jdk15on-148.jar" />
    <EmbeddedResource Include="Assets\Fmllib\deobfuscation_data_1.5.1.zip" />
    <EmbeddedResource Include="Assets\Fmllib\deobfuscation_data_1.5.2.zip" />
    <EmbeddedResource Include="Assets\Fmllib\deobfuscation_data_1.5.zip" />
    <EmbeddedResource Include="Assets\Fmllib\guava-12.0.1.jar" />
    <EmbeddedResource Include="Assets\Fmllib\guava-14.0-rc3.jar" />
    <EmbeddedResource Include="Assets\Fmllib\scala-library.jar" />
    <EmbeddedResource Include="Assets\launchWrapper-1.0.jar" />
  </ItemGroup>

</Project>