<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Tavstal.KonkordLauncher.Desktop</RootNamespace>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.2"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.2" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.2"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.2" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.2">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Markdown.Avalonia" Version="11.0.2" />
        <PackageReference Include="ReverseMarkdown" Version="4.7.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
      <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <AvaloniaResource Include="Styles\**" />
    </ItemGroup>
    
    <ItemGroup>
      <Compile Update="Views\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\AccountsWindow.axaml.cs">
        <DependentUpon>AccountsWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\CreateInstanceWindow.axaml.cs">
        <DependentUpon>CreateInstanceWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\StartupWindow.axaml.cs">
        <DependentUpon>StartupWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\InstallWindow.axaml.cs">
        <DependentUpon>InstallWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\EditInstanceWindow.axaml.cs">
        <DependentUpon>EditInstanceWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Models\Config\Instance\" />
    </ItemGroup>
</Project>
