using System.Collections.Generic;
using System.Text;
using Tavstal.KonkordLauncher.Common.Models;

namespace Tavstal.KonkordLauncher.Desktop;

public static class GlobalEvents
{
    #region Theme Change Event
    /// <summary>
    /// Delegate for handling theme change events.
    /// </summary>
    /// <param name="newTheme">The new theme that has been applied.</param>
    public delegate void ThemeChangedEventHandler(EThemeType newTheme);

    /// <summary>
    /// Event triggered when the application theme is changed.
    /// </summary>
    public static event ThemeChangedEventHandler? OnThemeChanged;

    /// <summary>
    /// Invokes the theme changed event with the specified new theme.
    /// </summary>
    /// <param name="newTheme">The new theme to apply.</param>
    public static void InvokeThemeChanged(EThemeType newTheme)
    {
        OnThemeChanged?.Invoke(newTheme);
    }
    #endregion

    #region Accounts Changed Event
    /// <summary>
    /// Delegate for handling accounts changed events.
    /// </summary>
    public delegate void AccountsChangedEventHandler();

    /// <summary>
    /// Event triggered when the accounts data is changed.
    /// </summary>
    public static event AccountsChangedEventHandler? OnAccountsChanged;

    /// <summary>
    /// Invokes the accounts changed event to notify subscribers of changes in the accounts data.
    /// </summary>
    public static void InvokeAccountsChanged()
    {
        OnAccountsChanged?.Invoke();
    }
    #endregion

    #region Instance Added Event

    /// <summary>
    /// Delegate used for subscribers that want to react when a new instance is created.
    /// </summary>
    /// <param name="instanceId">The ID of the instance that was added.</param>
    public delegate void InstanceAddedEventHandler(string instanceId);

    /// <summary>
    /// Raised when an instance is added to the launcher.
    /// Subscribers typically refresh instance lists or UI groups when this event fires.
    /// </summary>
    public static event InstanceAddedEventHandler? OnInstanceAdded;

    /// <summary>
    /// Invokes the <see cref="OnInstanceAdded"/> event with the specified instance ID.
    /// </summary>
    /// <param name="instanceId">The ID of the newly added instance.</param>
    public static void InvokeInstanceAdded(string instanceId) => OnInstanceAdded?.Invoke(instanceId);


    #endregion

    #region Instance Updated Event

    /// <summary>
    /// Delegate used for subscribers that want to react when an existing instance is updated.
    /// </summary>
    /// <param name="instanceId">The ID of the instance that was updated.</param>
    public delegate void InstanceUpdatedEventHandler(string instanceId);

    /// <summary>
    /// Raised when an instance is updated.
    /// Subscribers can refresh displayed metadata, icons, groups, or other UI state.
    /// </summary>
    public static event InstanceUpdatedEventHandler? OnInstanceUpdated;

    /// <summary>
    /// Invokes the <see cref="OnInstanceUpdated"/> event with the specified instance ID.
    /// </summary>
    /// <param name="instanceId">The ID of the updated instance.</param>
    public static void InvokeInstanceUpdated(string instanceId) => OnInstanceUpdated?.Invoke(instanceId);

    #endregion
    
    #region Instance Removed Event

    /// <summary>
    /// Delegate used for subscribers that want to react when an instance is removed.
    /// </summary>
    /// <param name="instanceId">The ID of the instance that was removed.</param>
    public delegate void InstanceRemovedEventHandler(string instanceId);

    /// <summary>
    /// Raised when an instance is removed from the launcher.
    /// Subscribers should remove the instance from any in-memory collections or UI lists.
    /// </summary>
    public static event InstanceRemovedEventHandler? OnInstanceRemoved;

    /// <summary>
    /// Invokes the <see cref="OnInstanceRemoved"/> event with the specified instance ID.
    /// </summary>
    /// <param name="instanceId">The ID of the removed instance.</param>
    public static void InvokeInstanceRemoved(string instanceId) => OnInstanceRemoved?.Invoke(instanceId);
    
    #endregion

    #region Instance Logged Event
    
    private static readonly Dictionary<string, string> _instanceLogs = new();
    public const int MaxLogSizeBytes = 10 * 1024 * 1024; // 10 MB

    /// <summary>
    /// Delegate for handling events when an instance logs a message.
    /// </summary>
    /// <param name="instanceId">The ID of the instance that generated the log message.</param>
    /// <param name="logMessage">The log message generated by the instance.</param>
    public delegate void InstanceLoggedEventHandler(string instanceId, string logMessage);

    /// <summary>
    /// Event triggered when an instance logs a message.
    /// Subscribers can listen to this event to handle log messages from instances.
    /// </summary>
    public static event InstanceLoggedEventHandler? OnInstanceLogged;

    /// <summary>
    /// Invokes the <see cref="OnInstanceLogged"/> event to notify subscribers of a log message from a specific instance.
    /// </summary>
    /// <param name="instanceId">The ID of the instance that generated the log message.</param>
    /// <param name="logMessage">The log message generated by the instance.</param>
    public static void InvokeInstanceLogged(string instanceId, string logMessage)
    {
        if (_instanceLogs.ContainsKey(instanceId))
        {
            _instanceLogs[instanceId] += logMessage;
            string log = _instanceLogs[instanceId];
            if (Encoding.UTF8.GetByteCount(log) > MaxLogSizeBytes)
            {
                int trimIndex = log.IndexOf('\n', log.Length / 2);
                if (trimIndex > 0)
                    _instanceLogs[instanceId] = log.Substring(trimIndex + 1);
            }
        }
        else 
            _instanceLogs.TryAdd(instanceId, logMessage);
        
        OnInstanceLogged?.Invoke(instanceId, logMessage);
    }

    /// <summary>
    /// Clears the logs for a specific instance by setting its log data to an empty string.
    /// </summary>
    /// <param name="instanceId">The ID of the instance whose logs should be cleared.</param>
    public static void CleareInstanceLogs(string instanceId)
    {
        if (_instanceLogs.ContainsKey(instanceId))
            _instanceLogs[instanceId] = string.Empty;
    }

    /// <summary>
    /// Retrieves the logs for a specific instance.
    /// </summary>
    /// <param name="instanceId">The ID of the instance whose logs should be retrieved.</param>
    /// <returns>
    /// A string containing the logs for the specified instance. 
    /// If no logs exist for the instance, an empty string is returned.
    /// </returns>
    public static string GetInstanceLogs(string instanceId)
    {
        return _instanceLogs.TryGetValue(instanceId, out var log) ? log : string.Empty;
    }
    #endregion
}