using System.Collections.Generic;
using Tavstal.KonkordLauncher.Common.Models;

namespace Tavstal.KonkordLauncher.Desktop;

public static class GlobalEvents
{
    #region Theme Change Event
    /// <summary>
    /// Delegate for handling theme change events.
    /// </summary>
    /// <param name="newTheme">The new theme that has been applied.</param>
    public delegate void ThemeChangedEventHandler(EThemeType newTheme);

    /// <summary>
    /// Event triggered when the application theme is changed.
    /// </summary>
    public static event ThemeChangedEventHandler? OnThemeChanged;

    /// <summary>
    /// Invokes the theme changed event with the specified new theme.
    /// </summary>
    /// <param name="newTheme">The new theme to apply.</param>
    public static void InvokeThemeChanged(EThemeType newTheme)
    {
        OnThemeChanged?.Invoke(newTheme);
    }
    #endregion

    #region Accounts Changed Event
    /// <summary>
    /// Delegate for handling accounts changed events.
    /// </summary>
    public delegate void AccountsChangedEventHandler();

    /// <summary>
    /// Event triggered when the accounts data is changed.
    /// </summary>
    public static event AccountsChangedEventHandler? OnAccountsChanged;

    /// <summary>
    /// Invokes the accounts changed event to notify subscribers of changes in the accounts data.
    /// </summary>
    public static void InvokeAccountsChanged()
    {
        OnAccountsChanged?.Invoke();
    }
    #endregion

    #region Instances Changed Event
    /// <summary>
    /// Delegate for handling events when the instances data changes.
    /// </summary>
    public delegate void InstancesChangedEventHandler();

    /// <summary>
    /// Event triggered when the instances data is changed.
    /// Subscribers can listen to this event to be notified of changes in instances.
    /// </summary>
    public static event InstancesChangedEventHandler? OnInstancesChanged;

    /// <summary>
    /// Invokes the <see cref="OnInstancesChanged"/> event to notify subscribers of changes in the instances data.
    /// </summary>
    public static void InvokeInstancesChanged()
    {
        OnInstancesChanged?.Invoke();
    }
    #endregion

    #region Instance Logged Event
    
    private static readonly Dictionary<string, string> _instanceLogs = new();

    /// <summary>
    /// Delegate for handling events when an instance logs a message.
    /// </summary>
    /// <param name="instanceId">The ID of the instance that generated the log message.</param>
    /// <param name="logMessage">The log message generated by the instance.</param>
    public delegate void InstanceLoggedEventHandler(string instanceId, string logMessage);

    /// <summary>
    /// Event triggered when an instance logs a message.
    /// Subscribers can listen to this event to handle log messages from instances.
    /// </summary>
    public static event InstanceLoggedEventHandler? OnInstanceLogged;

    /// <summary>
    /// Invokes the <see cref="OnInstanceLogged"/> event to notify subscribers of a log message from a specific instance.
    /// </summary>
    /// <param name="instanceId">The ID of the instance that generated the log message.</param>
    /// <param name="logMessage">The log message generated by the instance.</param>
    public static void InvokeInstanceLogged(string instanceId, string logMessage)
    {
        if (_instanceLogs.ContainsKey(instanceId))
            _instanceLogs[instanceId] += logMessage;
        else 
            _instanceLogs.TryAdd(instanceId, logMessage);
        OnInstanceLogged?.Invoke(instanceId, logMessage);
    }

    /// <summary>
    /// Clears the logs for a specific instance by setting its log data to an empty string.
    /// </summary>
    /// <param name="instanceId">The ID of the instance whose logs should be cleared.</param>
    public static void CleareInstanceLogs(string instanceId)
    {
        if (_instanceLogs.ContainsKey(instanceId))
            _instanceLogs[instanceId] = string.Empty;
    }

    /// <summary>
    /// Retrieves the logs for a specific instance.
    /// </summary>
    /// <param name="instanceId">The ID of the instance whose logs should be retrieved.</param>
    /// <returns>
    /// A string containing the logs for the specified instance. 
    /// If no logs exist for the instance, an empty string is returned.
    /// </returns>
    public static string GetInstanceLogs(string instanceId)
    {
        return _instanceLogs.TryGetValue(instanceId, out var log) ? log : string.Empty;
    }
    #endregion
}